install: true
language: generic
dist: trusty
sudo: false

before_script:
  - wget http://releases.ansible.com/ansible/ansible-latest.tar.gz
  - tar xf ansible-latest.tar.gz
  - chmod +x ansible-*/bin/*

script:
  - echo $VAULT_PASS > .vaultpass 2>/dev/null
  - ansible-*/bin/ansible-playbook playbook.yml -i inventory --vault-password-file=.vaultpass

after_script:
  - rm -f .vaultpass

branches:
  only:
    - master
