install: true

addons:
  apt:
    packages:
    - ansible

script:
  - echo $VAULT_PASS > .vaultpass 2>/dev/null
  - ansible-playbook playbook.yml -i inventory --vault-password-file=.vaultpass

after_script:
  - rm -f .vaultpass

branches:
  only:
    - master
