language: generic
dist: trusty
sudo: required


install: true

before_script:
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install ansible

script:
  - echo $VAULT_PASS > .vaultpass 2>/dev/null
  - ansible-playbook playbook.yml -i inventory --vault-password-file=.vaultpass

after_script:
  - rm -f .vaultpass

branches:
  only:
    - master
