language: generic
dist: trusty
sudo: required


install: true

before_script:
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -y
  - sudo apt-get install ansible -y

script:
  - echo $VAULT_PASS > ./vaultpass
  - ansible-playbook playbook.yml -i inventory --vault-password-file=./vaultpass

after_script:
  - rm -f ./vaultpass

branches:
  only:
    - master
