version: '3.1'

networks:
  traefik-network:
    external: true
  blogs-network:
    driver: overlay

services:
  papillon-en-allemagne:
    image: wordpress
    networks:
      - blogs-network
      - traefik-network
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:papillon-en-allemagne.docker.ab0.fr"
        - "traefik.docker.network=traefik-network"
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress_pea
      WORDPRESS_DB_HOST: mysql

  mysql:
    image: mysql:5.7
    user: "9000:9000"
    networks:
      - blogs-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "/var/swarm-data/volumes/ab0-blogs-mysql-data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - blogs-network
      - traefik-network
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:ab0-blogs.docker.ab0.fr,PathPrefixStrip:/phpmyadmin/;AddPrefix:/"
        - "traefik.docker.network=traefik-network"
        - "traefik.frontend.passHostHeader=true"
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: https://ab0-blogs.docker.ab0.fr/phpmyadmin/
